// Storing Characters
// X: Timeline
// Y: X coordinates of character
// Z: Y coordinates of character
//
// ......
// ......
// ......
// ......
// ......
//
// Input:
// ..##@.
// .#....
// ..##..
// ....#.
// .###..
//
// ...1x0
// ...000
// ......
// ......
// ......
//
// ...x1.
// ......
// ......
// ......
// ......

use EthanCoop::*;


fn main() {
    // let dim = (16, 16);
    // let grid_str = "
    //     .......########.
    //     ......########..
    //     .....#####......
    //     ....####........
    //     ...####.........
    //     ...#####........
    //     ....######......
    //     .....#######....
    //     .......######...
    //     ..........####..
    //     ...........####.
    //     ...........####.
    //     ..........####..
    //     .......######...
    //     ...#########....
    //     ..########......
    //
    // ";

    // For connecting points, find the shortest path that is farthest from all outer cells
    // Next point that is most in the center, then apply A* path finding
    //
    let mut canvas = Canvas::new();
    canvas.build_from_img("I.png");
    canvas.save();
}
